version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    command: python3 src/train.py
    volumes:
      - .:/app
