apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  template:
    spec:
      containers:
      - name: train
        image: rakeshthakkuri/car-price-train:latest
        command: ["python3", "src/train.py"]
      restartPolicy: Never
  backoffLimit: 2
