apiVersion: batch/v1
kind: Job
metadata:
  name: car-price-train
spec:
  template:
    metadata:
      labels:
        app: car-price-train
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: rakeshthakkuri/car-price-api:latest
          imagePullPolicy: Never
